version: 2.1
executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
commands:
  debug_output_dirlist:
    steps:
      - run: pwd && ls -la
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          keys:
            - npm-v1-{{ checksum "functions/package-lock.json" }}
            - npm
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v1-{{ checksum "functions/package-lock.json" }}
          paths:
            - ~/repo/functions/node_modules
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - debug_output_dirlist
      - run:
          name: Install npm
          command: pwd && npm install --save firebase-admin@latest firebase-functions@latest
      - run:
          name: Install dependencies
          command: pwd && npm install --save-dev firebase-tools@latest
      - save_npm
      - debug_output_dirlist
  deploy:
    parameters:
      env:
        type: enum
        enum: ["develop", "staging", "production"]
      project:
        type: enum
        enum: ["newagent-792a0"]
      firebase_admin_sdk:
        type: string
    executor:
      name: default
    steps:
      - checkout
#      - restore_npm
      - run:
          name: Install npm
          command: ls -la && npm install
      - run:
          name: Install dependencies
          command: cd functions && pwd && npm install --save-dev firebase-tools@latest
      - run:
          name: make json
          command: echo << parameters.firebase_admin_sdk >> >firebaseAdminSDK.json
      - debug_output_dirlist
      - run:
          name: Deploy to << parameters.env >> environment
          command: cd functions && node_modules/.bin/firebase deploy --only functions --project << parameters.project >> --token=$FIREBASE_TOKEN
      - debug_output_dirlist
workflows:
  setup_and_deploy:
    jobs:
#      - setup
      - deploy:
          name: deploy_dev
          env: develop
          project: newagent-792a0
          firebase_admin_sdk: $FIREBASE_ADMIN_SDK
#          requires:
#            - setup
          filters:
            branches:
              ignore:
                - release
                - master
      - deploy:
          name: deploy_stg
          env: staging
          project: newagent-792a0
          firebase_admin_sdk: $FIREBASE_ADMIN_SDK
#          requires:
#            - setup
          filters:
            branches:
              only: release*
      - deploy:
          name: deploy_prod
          env: production
          project: newagent-792a0
          firebase_admin_sdk: $FIREBASE_ADMIN_SDK
#          requires:
#            - setup
          filters:
            branches:
              only: master
              #only: release
